# Mod 2 - Project 2
## Salary Prediction Model for NYC Jobs

#### Deliverables
- A well-formed hypothesis and the question you are trying to answer 
- Data visualization showing correlations between variables and distributions of data
- Exploratory analysis of your data
- Results of your hypothesis testing with evaluation metrics (R square, coefficients of variables, your model)
- A model with at least **three** distinct independent variables, and **two** engineered features
- Examination of linear model assumptions using visualizations
- A coherent and insightful story

In [9]:
#!/usr/bin/env python

import pandas as pd
from sodapy import Socrata
import sqlite3
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
import matplotlib.pyplot as plt
%matplotlib inline


url = 'https://data.cityofnewyork.us/resource/kpav-sd4t.json'

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us", None)

# Max 4000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("kpav-sd4t", limit=4000)

# Convert to pandas DataFrame
df = pd.DataFrame.from_records(results)
print(df.shape)
df.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

,__of_positions,additional_information,agency,business_title,civil_service_title,division_work_unit,full_time_part_time_indicator,hours_shift,job_category,job_description,...,preferred_skills,process_date,residency_requirement,salary_frequency,salary_range_from,salary_range_to,title_code_no,to_apply,work_location,work_location_1
0,1,"Salary range for this position is: $42,405 - $...",DEPARTMENT OF BUSINESS SERV.,Account Manager,CONTRACT REVIEWER (OFFICE OF L,Strategy & Analytics,NaN,NaN,NaN,Division of Economic & Financial Opportunity (...,...,â€¢\tExcellent interpersonal and organizationa...,2019-04-16T00:00:00.000,New York City residency is generally required ...,Annual,42405,65485,40563,NaN,110 William St. N Y,NaN
1,1,NaN,DEPARTMENT OF BUSINESS SERV.,"EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT",ADMINISTRATIVE BUSINESS PROMOT,Tech Talent Pipeline,F,NaN,NaN,The New York City Department of Small Business...,...,NaN,2019-04-16T00:00:00.000,New York City residency is generally required ...,Annual,60740,162014,10009,"In addition to applying through this website, ...",110 William St. N Y,NaN
2,52,1. A Motor Vehicle Driverâ€™s License valid i...,NYC HOUSING AUTHORITY,Maintenance Worker - Technical Services-Heatin...,MAINTENANCE WORKER,Management Services Department,F,NaN,Maintenance & Operations,"Under direct supervision, assist in the routin...",...,1. A High School Diploma or GED. 2. CDL Dri...,2019-04-16T00:00:00.000,NYCHA has no residency requirements.,Annual,51907.68,54580.32,90698,"Click the ""Apply Now"" button.",Heating Mgt-Operations,NaN
3,52,1. A Motor Vehicle Driverâ€™s License valid i...,NYC HOUSING AUTHORITY,Maintenance Worker - Technical Services-Heatin...,MAINTENANCE WORKER,Management Services Department,F,NaN,Maintenance & Operations,"Under direct supervision, assist in the routin...",...,1. A High School Diploma or GED. 2. CDL Dri...,2019-04-16T00:00:00.000,NYCHA has no residency requirements.,Annual,51907.68,54580.32,90698,"Click the ""Apply Now"" button.",Heating Mgt-Operations,NaN
4,50,SPECIAL NOTE: 1. This is a temporary assig...,NYC HOUSING AUTHORITY,Temporary Painter,PAINTER,Dept of Management & Planning,F,NaN,Maintenance & Operations,Responsibilities of selected candidates will i...,...,NaN,2019-04-16T00:00:00.000,NYCHA has no residency requirement.,Hourly,35,35,91830,"Click the ""Apply Now"" button.",DMP-Contract & Analysis Unit,NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3494 entries, 0 to 3493
Data columns (total 27 columns):
__of_positions                   3494 non-null object
additional_information           2242 non-null object
agency                           3494 non-null object
business_title                   3494 non-null object
civil_service_title              3494 non-null object
division_work_unit               3494 non-null object
full_time_part_time_indicator    3217 non-null object
hours_shift                      1006 non-null object
job_category                     3492 non-null object
job_description                  3494 non-null object
job_id                           3494 non-null object
level                            3494 non-null object
minimum_qual_requirements        3474 non-null object
post_until                       1156 non-null object
posting_date                     3494 non-null object
posting_type                     3494 non-null object
posting_updated                  3494 non-null object
preferred_skills                 3017 non-null object
process_date                     3494 non-null object
residency_requirement            3494 non-null object
salary_frequency                 3494 non-null object
salary_range_from                3494 non-null object
salary_range_to                  3494 non-null object
title_code_no                    3494 non-null object
to_apply                         3493 non-null object
work_location                    3494 non-null object
work_location_1                  1497 non-null object
dtypes: object(27)
memory usage: 737.1+ KB

In [10]:
# Create SQL Database & Tables for Lionsgate WS Data
# Then create a dataframe for the data

conn = sqlite3.connect('nycjobs.db')
c = conn.cursor()
df.to_sql('AllNYCJobs', conn, if_exists='replace')

(3494, 27)

In [ ]:
### Export DataFrames to csv file

# df.to_csv('AllNYCJobs.csv')

#### SQL Queries for reference 

#print(c.execute('''SELECT * from Lionsgate_WS_S''').fetchall())
c.execute('''PRAGMA table_info(AllNYCJobs)''').fetchall()